FROM python:3.10-slim
ENV TZ="Europe/Amsterdam"
WORKDIR /app
COPY . /app/
RUN chmod -R 755 /app
RUN pip install --no-cache-dir -r requirements.txt
RUN pip show python-socketio
EXPOSE 8000
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["uvicorn", "main:socket_app", "--host", "0.0.0.0", "--port", "8000"]

